import { Typography, Container } from "@mui/material";
import React from "react";

function TandCs() {
  return (
    <Container maxWidth="md" sx={{ textAlign: "left", marginTop: "4rem" }}>
      <Typography variant="h3">Terms & Conditions</Typography> <br /> <br />
      <br />
      <Typography variant="p">
        This document is an electronic record in terms of Information Technology
        Act, 2000 and rules there under as applicable and the amended provisions
        pertaining to electronic records in various statutes as amended by the
        Information Technology Act, 2000. This electronic record is generated by
        a computer system and does not require any physical or digital
        signatures.
        <br /> <br />
        <br />
        This document is published in accordance with the provisions of Rule 3
        (1) of the Information Technology (Intermediaries guidelines) Rules,
        2011 that require publishing the rules and regulations, privacy policy
        and Terms of Use for access or usage of domain name [www.GreenKart.com]
        (“Website”), including the related mobile site and mobile application
        (hereinafter referred to as “Platform”) The Platform is owned by
        Liontech Solutions Private Limited a company incorporated under the
        Companies Act, 1956 with its registered office at 7, Cityratna Appt.
        Near Shitla Kund, Jay Shri Cinema Road, Junagadh, Gujarat, India.
        <br /> <br />
        <br />
        Your use of the Platform and services and tools are governed by the
        following terms and conditions ("Terms of Use") as applicable to the
        Platform. If you do any transaction on the Platform, You shall be
        subject to the policies that are applicable to the Platform for such
        transaction. Any use of the Platform and you shall be contracting with
        Liontech Solutions Private Limited and these terms and conditions
        including other policies constitute your binding obligations, with
        GreenKart.
        <br /> <br />
        <br />
        For the purpose of these Terms of Use, wherever the context so requires
        "You" or "User" shall mean any natural or legal person who has agreed to
        become a buyer on the Platform by providing Registration Data while
        registering on the Platform as Registered User using the computer
        systems or any other device. GreenKart allows the User to surf the
        Platform or making purchases without registering on the Platform. The
        term "We", "Us", "Our" shall mean Liontech Solutions Private Limited.
        <br /> <br />
        <br />
        When You use any of the services provided by Us (GreenKart) through the
        Platform, including but not limited to, (e.g. Product Reviews, Seller
        Reviews), You will be subject to the rules, guidelines, policies, terms,
        and conditions applicable to such service, and they shall be deemed to
        be incorporated into this Terms of Use and shall be considered as part
        and parcel of this Terms of Use. We, Liontech Solutions Private Limited
        reserve the right, at our sole discretion, to change, modify, add or
        remove portions of these Terms of Use, at any time without any prior
        written notice to you. It is your responsibility to review these Terms
        of Use periodically for updates / changes. Your continued use of the
        Platform following the posting of changes will mean that you accept and
        agree to the revisions. As long as you comply with these Terms of Use,
        We grant you a personal, non-exclusive, non-transferable, limited
        privilege to enter and use the Platform.
        <br /> <br />
        <br />
        ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT
        TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ
        THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
        <br /> <br />
        <br />
        By impliedly or expressly accepting these Terms of Use, You also accept
        and agree to be bound by GreenKart Policies ((including but not limited
        to Privacy Policy available at Privacy) as amended from time to time.
        <br /> <br />
        <br />
        <strong> Transaction Eligibility</strong>
        <br />
        Transaction on the Platform is available only to persons who can form
        legally binding contracts under Indian Contract Act, 1872. Persons who
        are "incompetent to contract" within the meaning of the Indian Contract
        Act, 1872 including un-discharged insolvents etc. are not eligible to
        use the Platform. If you are a minor i.e. under the age of 18 years, you
        may use the Platform or access content on the Platform only under the
        supervision and prior consent/ permission of a parent or legal guardian.
        <br /> <br />
        <br />
        As a minor if you wish to transact on the Platform, such transaction on
        the Platform may be made by your legal guardian or parents. GreenKart
        reserves the right to terminate your transaction and / or refuse to
        provide you with access to the Platform if it is brought to our notice
        or if it is discovered that you are under the age of 18 years and
        transacting on the Platform.
        <br /> <br />
        <br />
        <strong> Account and Registration Obligations</strong>
        <br />
        If you use the Platform, You shall be responsible for maintaining the
        confidentiality of your Display Name and Password and you shall be
        responsible for all activities that occur under your Display Name and
        Password. You agree that if You provide any information that is untrue,
        inaccurate, not current or incomplete or We have reasonable grounds to
        suspect that such information is untrue, inaccurate, not current or
        incomplete, or not in accordance with the this Terms of Use, We shall
        have the right to indefinitely suspend or terminate or block access of
        your membership on the Platform and refuse to provide You with access to
        the Platform.
        <br /> <br />
        <br />
        Your mobile phone number and/or e-mail address is treated as your
        primary identifier on the Platform. It is your responsibility to ensure
        that your mobile phone number and your email address is up to date on
        the Platform at all times. You agree to notify us promptly if your
        mobile phone number or e-mail address changes by updating the same on
        the Platform through a one time password (OTP) verification.
        <br /> <br />
        <br />
        <strong> Communications</strong>
        <br />
        When You use the Platform or send emails or other data, information or
        communication to us, You agree, believe and understand that You are
        communicating with GreenKart through electronic records and You consent
        to receive communications via electronic records from us periodically
        and as and when required. We may communicate with you by email, SMS or
        by such other mode of communication, electronic or otherwise. The User
        hereby consents, expresses and agrees that he has read and fully
        understands the Privacy Policy of GreenKart.com The User hereby agrees
        to receive sms and email notifications on his/her registered mobile
        number. The user further consents that the terms and contents of such
        Privacy Policy are acceptable to him.
        <br /> <br />
        <br />
        <strong> Products and Services</strong>
        <br />
        GreenKart is not responsible for unsatisfactory or delayed performance
        of services or damages or delays as a result of products which are out
        of stock, unavailable or back ordered.
        <br /> <br />
        <br />
        All Products sold on GreenKart are genuine. Products sold on the
        platform are purchased via legal channels or directly from the Company.
        GreenKart holds no liability or responsibility for the performance of
        any product.
        <br /> <br />
        <br />
        Disclaimer: Pricing on any product(s) as is reflected on the Platform
        may due to some technical issue, typographical error or product
        information published by GreenKart may be incorrectly reflected and in
        such an event GreenKart may cancel such order(s).
        <br /> <br />
        <br />
        <strong> Platform Usage fees</strong>
        <br />
        GreenKart does not charge any fee for browsing and buying on the
        Platform.
        <br /> <br />
        <br />
        <strong> Use of the Platform GreenKart</strong>
        <br />
        You agree, undertake and confirm that your use of Platform shall be
        strictly governed by the following binding principles:
        <br /> <br />
        <br />
        1. You shall not host, display, upload, modify, publish, transmit,
        update or share any information which:
        <br />
        (a) belongs to another person and to which You does not have any right
        to;
        <br /> <br />
        (b) is grossly harmful, harassing, blasphemous, defamatory, obscene,
        pornographic, paedophilic, libellous, invasive of another's privacy,
        hateful, or racially, ethnically objectionable, disparaging, relating or
        encouraging money laundering or gambling, or otherwise unlawful in any
        manner whatever; or unlawfully threatening or unlawfully harassing
        including but not limited to "indecent representation of women" within
        the meaning of the Indecent Representation of Women (Prohibition) Act,
        1986;
        <br /> <br />
        (c) is misleading in any way;
        <br /> <br />
        (d) harasses or advocates harassment of another person;
        <br /> <br />
        (e) is patently offensive to the online community, such as sexually
        explicit content, or content that promotes obscenity, paedophilia,
        racism, bigotry, hatred or physical harm of any kind against any group
        or individual;
        <br /> <br />
        (f) involves the transmission of "junk mail", "chain letters", or
        unsolicited mass mailing or "spamming";
        <br /> <br />
        (g) infringes upon or violates any third party's rights [including, but
        not limited to, intellectual property rights, rights of privacy
        (including without limitation unauthorized disclosure of a person's
        name, email address, physical address or phone number) or rights of
        publicity];
        <br /> <br />
        (h) promotes illegal activities or conduct that is abusive, threatening,
        obscene, defamatory or libellous;
        <br /> <br />
        (i) promotes an illegal or unauthorized copy of another person's
        copyrighted work (see "Copyright complaint" below for instructions on
        how to lodge a complaint about uploaded copyrighted material), such as
        providing pirated computer programs or links to them, providing
        information to circumvent manufacture-installed copy-protect devices, or
        providing pirated music or links to pirated music files;
        <br /> <br />
        (j) contains restricted or password-only access pages, or hidden pages
        or images (those not linked to or from another accessible page);
        <br /> <br />
        (k) provides material that exploits people in a sexual, violent or
        otherwise inappropriate manner or solicits personal information from
        anyone;
        <br /> <br />
        (l) contains video, photographs, or images of another person (with a
        minor or an adult).
        <br /> <br />
        (m) provides instructional information about illegal activities such as
        making or buying illegal weapons, violating someone's privacy, or
        providing or creating computer viruses;
        <br /> <br />
        (n) tries to gain unauthorized access or exceeds the scope of authorized
        access to the Platform or to profiles, blogs, communities, account
        information, bulletins, friend request, or other areas of the Platform
        or solicits passwords or personal identifying information for commercial
        or unlawful purposes from other users;
        <br /> <br />
        (o) solicits gambling or engages in any gambling activity which We, in
        Our sole discretion, believes is or could be construed as being illegal;
        <br /> <br />
        (p) engages in commercial activities and/or sales without Our prior
        written consent such as contests, sweepstakes, barter, advertising and
        pyramid schemes, or the buying or selling of "virtual" products related
        to the Platform. Throughout this Terms of Use, GreenKart’s prior written
        consent means a communication coming from GreenKart’s Legal Department,
        specifically in response to your request, and specifically addressing
        the activity or conduct for which You seek authorization;
        <br /> <br />
        (q) interferes with another USER's use and enjoyment of the Platform or
        any other individual's User and enjoyment of similar services;
        <br /> <br />
        (r) refers to any Platform or URL that, in Our sole discretion, contains
        material that is inappropriate for the Platform or any other Platform,
        contains content that would be prohibited or violates the letter or
        spirit of these Terms of Use.
        <br /> <br />
        (s) harm minors in any way;
        <br /> <br />
        (t) infringes any patent, trademark, copyright or other proprietary
        rights or third party's trade secrets or rights of publicity or privacy
        or shall not be fraudulent or involve the sale of counterfeit or stolen
        products;
        <br /> <br />
        (u) violates any law for the time being in force;
        <br /> <br />
        (v) deceives or misleads the addressee/ users about the origin of such
        messages or communicates any information which is grossly offensive or
        menacing in nature;
        <br /> <br />
        (w) impersonate another person;
        <br /> <br />
        (x) contains software viruses or any other computer code, files or
        programs designed to interrupt, destroy or limit the functionality of
        any computer resource; or contains any trojan horses, worms, time bombs,
        cancelbots, easter eggs or other computer programming routines that may
        damage, detrimentally interfere with, diminish value of, surreptitiously
        intercept or expropriate any system, data or personal information;
        <br /> <br />
        (y) threatens the unity, integrity, defence, security or sovereignty of
        India, friendly relations with foreign states, or public order or causes
        incitement to the commission of any cognizable offence or prevents
        investigation of any offence or is insulting any other nation.
        <br /> <br />
        (z) shall not be false, inaccurate or misleading;
        <br /> <br />
        (aa) shall not, directly or indirectly, offer, attempt to offer, trade
        or attempt to trade in any item, the dealing of which is prohibited or
        restricted in any manner under the provisions of any applicable law,
        rule, regulation or guideline for the time being in force.
        <br /> <br />
        (ab) shall not create liability for Us or cause Us to lose (in whole or
        in part) the services of Our internet service provider ("ISPs") or other
        suppliers;
        <br /> <br />
        <br />
        1. You shall not use any "deep-link", "page-scrape", "robot", "spider"
        or other automatic device, program, algorithm or methodology, or any
        similar or equivalent manual process, to access, acquire, copy or
        monitor any portion of the Platform or any Content, or in any way
        reproduce or circumvent the navigational structure or presentation of
        the Platform or any Content, to obtain or attempt to obtain any
        materials, documents or information through any means not purposely made
        available through the Platform. We reserve our right to bar any such
        activity.
        <br /> <br />
        <br />
        2. You shall not attempt to gain unauthorized access to any portion or
        feature of the Platform, or any other systems or networks connected to
        the Platform or to any server, computer, network, or to any of the
        services offered on or through the Platform, by hacking, password
        "mining" or any other illegitimate means.
        <br /> <br />
        <br />
        3. You shall not probe, scan or test the vulnerability of the Platform
        or any network connected to the Platform nor breach the security or
        authentication measures on the Platform or any network connected to the
        Platform. You may not reverse look-up, trace or seek to trace any
        information on any other User of or visitor to Platform, or any other
        customer, including any account on the Platform not owned by You, to its
        source, or exploit the Platform or any service or information made
        available or offered by or through the Platform, in any way where the
        purpose is to reveal any information, including but not limited to
        personal identification or information, other than Your own information,
        as provided for by the Platform.
        <br /> <br />
        <br />
        4. You shall not make any negative, denigrating or defamatory
        statement(s) or comment(s) about Us or the brand name or domain name
        used by Us including the terms GreenKart.com, or otherwise engage in any
        conduct or action that might tarnish the image or reputation, of
        GreenKart or sellers on platform or otherwise tarnish or dilute any
        GreenKart's trade or service marks, trade name and/or goodwill
        associated with such trade or service marks, trade name as may be owned
        or used by us. You agree that you will not take any action that imposes
        an unreasonable or disproportionately large load on the infrastructure
        of the Platform or GreenKart's systems or networks, or any systems or
        networks connected to GreenKart.
        <br /> <br />
        <br />
        5. You agree not to use any device, software or routine to interfere or
        attempt to interfere with the proper working of the Platform or any
        transaction being conducted on the Platform, or with any other person's
        use of the Platform.
        <br /> <br />
        <br />
        6. You may not forge headers or otherwise manipulate identifiers in
        order to disguise the origin of any message or transmittal that you send
        to Us on or through the Platform or any service offered on or through
        the Platform. You may not pretend that You are, or that You represent,
        someone else, or impersonate any other individual or entity.
        <br /> <br />
        <br />
        7. You may not use the Platform or any content for any purpose that is
        unlawful or prohibited by these Terms of Use, or to solicit the
        performance of any illegal activity or other activity which infringes
        the rights of GreenKart and / or others.
        <br /> <br />
        <br />
        8. You shall at all times ensure full compliance with the applicable
        provisions of the Information Technology Act, 2000 and rules there under
        as applicable and as amended from time to time and also all applicable
        Domestic laws, rules and regulations (including the provisions of any
        applicable Exchange Control Laws or Regulations in Force) and
        International Laws, Foreign Exchange Laws, Statutes, Ordinances and
        Regulations (including, but not limited to Sales Tax/VAT, Income Tax,
        Octroi, Service Tax, Central Excise, Custom Duty, Local Levies)
        regarding Your use of Our service and Your listing, purchase,
        solicitation of offers to purchase, and sale of products or services.
        You shall not engage in any transaction in an item or service, which is
        prohibited by the provisions of any applicable law including exchange
        control laws or regulations for the time being in force.
        <br /> <br />
        <br />
        9. Solely to enable Us to use the information You supply Us with, so
        that we are not violating any rights You might have in Your Information,
        You agree to grant Us a non-exclusive, worldwide, perpetual,
        irrevocable, royalty-free, sub-licensable (through multiple tiers) right
        to exercise the copyright, publicity, database rights or any other
        rights You have in Your Information, in any media now known or not
        currently known, with respect to Your Information. We will only use Your
        information in accordance with the Terms of Use and Privacy Policy
        applicable to use of the Platform.
        <br /> <br />
        <br />
        10. From time to time, You shall be responsible for providing
        information relating to the products or services proposed to be sold by
        You. In this connection, You undertake that all such information shall
        be accurate in all respects. You shall not exaggerate or over emphasize
        the attributes of such products or services so as to mislead other Users
        in any manner.
        <br /> <br />
        <br />
        11. You shall not engage in advertising to, or solicitation of, other
        Users of the Platform to buy or sell any products or services,
        including, but not limited to, products or services related to that
        being displayed on the Platform or related to us. You may not transmit
        any chain letters or unsolicited commercial or junk email to other Users
        via the Platform. It shall be a violation of these Terms of Use to use
        any information obtained from the Platform in order to harass, abuse, or
        harm another person, or in order to contact, advertise to, solicit, or
        sell to another person other than Us without Our prior explicit consent.
        In order to protect Our Users from such advertising or solicitation, We
        reserve the right to restrict the number of messages or emails which a
        user may send to other Users in any 24-hour period which We deems
        appropriate in its sole discretion. You understand that We have the
        right at all times to disclose any information (including the identity
        of the persons providing information or materials on the Platform) as
        necessary to satisfy any law, regulation or valid governmental request.
        This may include, without limitation, disclosure of the information in
        connection with investigation of alleged illegal activity or
        solicitation of illegal activity or in response to a lawful court order
        or subpoena. In addition, We can (and You hereby expressly authorize Us
        to) disclose any information about You to law enforcement or other
        government officials, as we, in Our sole discretion, believe necessary
        or appropriate in connection with the investigation and/or resolution of
        possible crimes, especially those that may involve personal injury.
        <br /> <br />
        <br />
        12. Your correspondence or business dealings with, or participation in
        promotions of, advertisers found on or through the Platform, including
        payment and delivery of related products or services, and any other
        terms, conditions, warranties or representations associated with such
        dealings, are solely between You and such advertiser. We shall not be
        responsible or liable for any loss or damage of any sort incurred as the
        result of any such dealings or as the result of the presence of such
        advertisers on the Platform.
        <br /> <br />
        <br />
        13. It is possible that other users (including unauthorized users or
        "hackers") may post or transmit offensive or obscene materials on the
        Platform and that You may be involuntarily exposed to such offensive and
        obscene materials. It also is possible for others to obtain personal
        information about You due to your use of the Platform, and that the
        recipient may use such information to harass or injure You. We does not
        approve of such unauthorized uses, but by using the Platform You
        acknowledge and agree that We are not responsible for the use of any
        personal information that You publicly disclose or share with others on
        the Platform. Please carefully select the type of information that You
        publicly disclose or share with others on the Platform.
        <br /> <br />
        <br />
        14. GreenKart shall have all the rights to take necessary action and
        claim damages that may occur due to your involvement/participation in
        any way on your own or through group/s of people, intentionally or
        unintentionally in DoS/DDoS (Distributed Denial of Services).
        <br /> <br />
        <br />
        15. You acknowledge and agree that the regional language features are
        made available on the Platform on a reasonable effort basis for
        convenience only, without any representation or warranties by GreenKart,
        express or implied, including the translations being error free, their
        accuracy, completeness or reliability.
      </Typography>{" "}
    </Container>
  );
}

export default TandCs;
